FROM ubuntu:noble


RUN apt -y update && apt -y install software-properties-common python3-launchpadlib && \
    add-apt-repository -y ppa:oisf/suricata-stable && \
    apt -y update && apt -y install suricata=1:7.0.10-0ubuntu0


RUN suricata -V